version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"